export const mockSchedules = {
  code: 0,
  message: {
    schedules: [
      {
        schedule_id: 7280,
        doctor_id: 595,
        doctor_name: '于博',
        department_id: 29,
        department_name: '妇产科',
        clinic_type: '普通门诊',
        date: '2025-11-27',
        time_slot: '上午',
        total_slots: 20,
        remaining_slots: 20,
        available_slot_types: ['普通'],
      },
    ],
  },
}

export const mockQueueData = {
  stats: {
    totalSlots: 50,
    waitingCount: 5,
    completedCount: 10,
    passedCount: 1,
  },
  currentPatient: {
    orderId: '1001',
    patientId: 'P001',
    patientName: '张三',
    queueNumber: 'A005',
    gender: '男',
    age: 30,
    visitTime: '10:00',
    passCount: 0,
  },
  nextPatient: {
    patientName: '李四',
    queueNumber: 'A006',
  },
  queue: [
    {
      orderId: '1002',
      patientId: 'P002',
      patientName: '李四',
      queueNumber: 'A006',
      gender: '女',
      age: 28,
      visitTime: '10:15',
      passCount: 0,
    },
    {
      orderId: '1003',
      patientId: 'P003',
      patientName: '王五',
      queueNumber: 'A007',
      gender: '男',
      age: 45,
      visitTime: '10:30',
      passCount: 0,
    },
    {
      orderId: '1004',
      patientId: 'P004',
      patientName: '赵六',
      queueNumber: 'A008',
      gender: '女',
      age: 32,
      visitTime: '10:45',
      passCount: 0,
    },
    {
      orderId: '1005',
      patientId: 'P005',
      patientName: '孙七',
      queueNumber: 'A009',
      gender: '男',
      age: 50,
      visitTime: '11:00',
      passCount: 0,
    },
    {
      orderId: '1006',
      patientId: 'P006',
      patientName: '周八',
      queueNumber: 'A010',
      gender: '女',
      age: 22,
      visitTime: '11:15',
      passCount: 0,
    },
  ],
  waitlist: [
    {
      orderId: '1000',
      patientId: 'P000',
      patientName: '过号王',
      queueNumber: 'A004',
      gender: '男',
      age: 60,
      visitTime: '09:45',
      passCount: 1,
    },
  ],
  completedList: [
    {
      orderId: '0999',
      patientId: 'P099',
      patientName: '赵四',
      queueNumber: 'A001',
      gender: '男',
      age: 35,
      visitTime: '09:00',
      passCount: 0,
    },
    {
      orderId: '0998',
      patientId: 'P098',
      patientName: '钱五',
      queueNumber: 'A002',
      gender: '女',
      age: 29,
      visitTime: '09:15',
      passCount: 0,
    },
  ],
  invalidList: [],
}

export const mockPatients = {
  patients: [
    {
      patient_id: 'P001',
      name: '王五',
      gender: '男',
      age: 25,
      phone: '13800000000',
    },
    {
      patient_id: 'P002',
      name: '张三',
      gender: '男',
      age: 30,
      phone: '13900000000',
    },
  ],
}
